(function() {
	var list = [{
		question: '您在团贷网已经投资了多久？',
		options: [{
			id: 0,
			text: '1个月以内'
		}, {
			id: 1,
			text: '1-3个月'
		}, {
			id: 2,
			text: '3-6个月'
		}, {
			id: 3,
			text: '6-12个月'
		}, {
			id: 4,
			text: '12个月以上'
		}],
		id: 0,
		limit: 1,
		recomment: ''
	}, {
		question: '银行存管上线前，您对团贷网投资过程中的整体体验是否满意？',
		options: [{
			id: 0,
			text: '非常满意'
		}, {
			id: 1,
			text: '比较满意'
		}, {
			id: 2,
			text: '不是很满意'
		}, {
			id: 3,
			text: '十分不满意'
		}, {
			id: 4,
			text: '尚未体验完毕，不确定'
		}],
		id: 1,
		limit: 1,
		recomment: ''
	}, {
		question: '您在开通银行存管账户过程中，是否出现过困难？',
		options: [{
			id: 0,
			text: '是',
			showSub: 1 //是否显示分支
		}, {
			id: 1,
			text: '否',
			showSub: 0
		}],
		id: 2,
		limit: 1,
		recomment: '',
		hasBrench: true, //是否有分支
		subQuestion: [{
			id: 0,
			question: '您在开通银行存管账户过程中出现问题后，是否能及时联系客服？',
			subOptions: [{
				id: 0,
				text: '是，联系客服后，在客服协助下顺利解决问题'
			}, {
				id: 1,
				text: '是，但等候人数很多，等候时间在1小时以上'
			}, {
				id: 2,
				text: '否，前面等候人数太多，等候时间需要1天以上，当天没法及时联系上'
			}, {
				id: 3,
				text: '否，不知道如何联系客服'
			}, {
				id: 4,
				text: '否，原因',
				hasInput: true //是否有输入
			}],
			limit: 1
		}, {
			id: 1,
			question: '您对客服的服务态度是否满意？',
			subOptions: [{
				id: 0,
				text: '非常满意'
			}, {
				id: 1,
				text: '比较满意'
			}, {
				id: 2,
				text: '不是很满意'
			}, {
				id: 3,
				text: '十分不满意'
			}],
			limit: 1
		}, {
			id: 2,
			question: '您在开通银行存管账户过程中出现问题后，多久得到解决？',
			subOptions: [{
				id: 0,
				text: '1天内'
			}, {
				id: 1,
				text: '1-3天'
			}, {
				id: 2,
				text: '3-7天'
			}, {
				id: 3,
				text: '7天以上'
			}, {
				id: 4,
				text: '至今尚未解决'
			}]
		}, {
			id: 3,
			question: '您对于银行存管对接期间，平台解决问题的速度是否满意？',
			subOptions: [{
				id: 0,
				text: '非常满意'
			}, {
				id: 1,
				text: '比较满意'
			}, {
				id: 2,
				text: '不是很满意'
			}, {
				id: 3,
				text: '十分不满意'
			}]
		}]
	}, {
		question: '银行存管上线后，您体验过以下哪些流程？',
		options: [{
			id: 0,
			text: '充值'
		}, {
			id: 1,
			text: '提现'
		}, {
			id: 2,
			text: '还款'
		}, {
			id: 3,
			text: '借款'
		}, {
			id: 4,
			text: '以上流程都还没体验',
			only: true //是否与其他选项互斥
		}],
		id: 3,
		limit: 7,
		recomment: '(不定项选择)'
	}, {
		question: '您是否了解银行存管上线后提现时间的变化？',
		options: [{
			id: 0,
			text: '了解',
		}, {
			id: 1,
			text: '不了解'
		}],
		id: 4,
		limit: 1,
		recomment: ''
	}, {
		question: '您是否了解银行存管上线后用户资金有什么有变化？',
		options: [{
			id: 0,
			text: '是'
		}, {
			id: 1,
			text: '否'
		}],
		id: 5,
		limit: 1,
		recomment: ''
	}, {
		question: '对于银行存管对接过程中所出现的问题，您的态度是？',
		options: [{
			id: 0,
			text: '十分理解，相信平台会尽快处理好'
		}, {
			id: 1,
			text: '可以理解，但感觉处理问题速度比较慢'
		}, {
			id: 2,
			text: '不能理解，对平台处理问题的速度不满意'
		}, {
			id: 3,
			text: '完全无法理解，对于在团贷网投资的信心有一定影响'
		}],
		id: 6,
		limit: 1,
		recomment: ''
	}, {
		question: '实现银行存管后，对于您在团贷网投资产生了什么影响？',
		options: [{
			id: 0,
			text: '没有任何影响，一切如常地进行投资'
		}, {
			id: 1,
			text: '投资更有信心，打算加大在团贷网的投资额度'
		}, {
			id: 2,
			text: '存管过程中出现的技术问题，对投资信心有一定影响'
		}, {
			id: 3,
			text: '现在还不确定'
		}],
		id: 7,
		limit: 1,
		recomment: '',
	}, {
		question: '总体来说，您对团贷网银行存管上线期间的服务是否满意？',
		options: [{
			id: 0,
			text: '满意'
		}, {
			id: 1,
			text: '还行'
		}, {
			id: 2,
			text: '不满意'
		}],
		id: 8,
		limit: 1,
		recomment: '',
	}, {
		question: '分享一下您在团贷网实现银行存管期间的感受及建议',
		options: [],
		id: 9,
		limit: 1,
		recomment: '（选填）',
	}];
	window.list = list;
})();